### ISSUE TITLE
Fix website typos smh

### ISSUE THREAD

**Issue by CitrionDragon** [Lotus-AU/LotusContinued#6]
Its bugging me now that I can see it, and I cant fix it myself. Should be https://beta.lotusau.top/ and not beta.lotusuau.top.
![Screenshot 2024-09-19 170234](https://github.com/user-attachments/assets/e4462b02-c2d7-4dcd-96c1-3c8e5ffb3b1e)

**Comment by ThetaHalo** [comment]
fixed
